# Generated by Django 4.2.16 on 2024-10-13 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhyChooseMainPage',
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact us'},
        ),
        migrations.AlterModelOptions(
            name='counter',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='subscribe',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='whychooseus',
            options={'verbose_name_plural': 'Why choose us'},
        ),
        migrations.RemoveField(
            model_name='partner',
            name='hover_image',
        ),
    ]
